[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "june-grpc-api"
version = "0.1.0"
description = "June shared gRPC API (protos + generated Python stubs at build time)"
authors = [{name = "June Team"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "grpcio>=1.56.0",
]

[tool.setuptools]
packages = [
  "june_grpc_api",
  "june_grpc_api.generated",
  "june_grpc_api.shim",
]
include-package-data = true

[tool.setuptools.package-data]
"june_grpc_api" = ["*.py"]
"june_grpc_api.generated" = ["*.py"]




