# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in llm_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LLMInferenceStub(object):
    """LLM Inference Service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStream = channel.unary_stream(
            "/june.llm.LLMInference/GenerateStream",
            request_serializer=llm__pb2.GenerationRequest.SerializeToString,
            response_deserializer=llm__pb2.GenerationChunk.FromString,
            _registered_method=True,
        )
        self.Generate = channel.unary_unary(
            "/june.llm.LLMInference/Generate",
            request_serializer=llm__pb2.GenerationRequest.SerializeToString,
            response_deserializer=llm__pb2.GenerationResponse.FromString,
            _registered_method=True,
        )
        self.ChatStream = channel.unary_stream(
            "/june.llm.LLMInference/ChatStream",
            request_serializer=llm__pb2.ChatRequest.SerializeToString,
            response_deserializer=llm__pb2.ChatChunk.FromString,
            _registered_method=True,
        )
        self.Chat = channel.unary_unary(
            "/june.llm.LLMInference/Chat",
            request_serializer=llm__pb2.ChatRequest.SerializeToString,
            response_deserializer=llm__pb2.ChatResponse.FromString,
            _registered_method=True,
        )
        self.Embed = channel.unary_unary(
            "/june.llm.LLMInference/Embed",
            request_serializer=llm__pb2.EmbeddingRequest.SerializeToString,
            response_deserializer=llm__pb2.EmbeddingResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/june.llm.LLMInference/HealthCheck",
            request_serializer=llm__pb2.HealthRequest.SerializeToString,
            response_deserializer=llm__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class LLMInferenceServicer(object):
    """LLM Inference Service"""

    def GenerateStream(self, request, context):
        """Streaming generation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Generate(self, request, context):
        """One-shot generation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChatStream(self, request, context):
        """Streaming chat"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Chat(self, request, context):
        """One-shot chat"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Embed(self, request, context):
        """Embedding generation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LLMInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateStream": grpc.unary_stream_rpc_method_handler(
            servicer.GenerateStream,
            request_deserializer=llm__pb2.GenerationRequest.FromString,
            response_serializer=llm__pb2.GenerationChunk.SerializeToString,
        ),
        "Generate": grpc.unary_unary_rpc_method_handler(
            servicer.Generate,
            request_deserializer=llm__pb2.GenerationRequest.FromString,
            response_serializer=llm__pb2.GenerationResponse.SerializeToString,
        ),
        "ChatStream": grpc.unary_stream_rpc_method_handler(
            servicer.ChatStream,
            request_deserializer=llm__pb2.ChatRequest.FromString,
            response_serializer=llm__pb2.ChatChunk.SerializeToString,
        ),
        "Chat": grpc.unary_unary_rpc_method_handler(
            servicer.Chat,
            request_deserializer=llm__pb2.ChatRequest.FromString,
            response_serializer=llm__pb2.ChatResponse.SerializeToString,
        ),
        "Embed": grpc.unary_unary_rpc_method_handler(
            servicer.Embed,
            request_deserializer=llm__pb2.EmbeddingRequest.FromString,
            response_serializer=llm__pb2.EmbeddingResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=llm__pb2.HealthRequest.FromString,
            response_serializer=llm__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "june.llm.LLMInference", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("june.llm.LLMInference", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LLMInference(object):
    """LLM Inference Service"""

    @staticmethod
    def GenerateStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/june.llm.LLMInference/GenerateStream",
            llm__pb2.GenerationRequest.SerializeToString,
            llm__pb2.GenerationChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Generate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/june.llm.LLMInference/Generate",
            llm__pb2.GenerationRequest.SerializeToString,
            llm__pb2.GenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChatStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/june.llm.LLMInference/ChatStream",
            llm__pb2.ChatRequest.SerializeToString,
            llm__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Chat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/june.llm.LLMInference/Chat",
            llm__pb2.ChatRequest.SerializeToString,
            llm__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Embed(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/june.llm.LLMInference/Embed",
            llm__pb2.EmbeddingRequest.SerializeToString,
            llm__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/june.llm.LLMInference/HealthCheck",
            llm__pb2.HealthRequest.SerializeToString,
            llm__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
