#!/bin/bash
# Helper script to generate docker-compose.yml service snippets for Riva NIMs
#
# This script generates docker-compose.yml service definitions for Riva ASR/TTS NIMs
# following the nim-qwen3 pattern. Use this after verifying NIM compatibility.
#
# Usage:
#   ./scripts/generate_nim_compose_snippet.sh [--stt] [--tts] [--image IMAGE] [--name NAME] [--grpc-port PORT] [--http-port PORT]
#
# Options:
#   --stt          Generate STT (Riva ASR) NIM service snippet
#   --tts          Generate TTS (Riva TTS) NIM service snippet
#   --image IMAGE   Docker image path (e.g., nvcr.io/nim/riva/riva-asr:1.0.0)
#   --name NAME     Service name (e.g., nim-riva-asr)
#   --grpc-port     gRPC port (default: 8001 for LLM, 8002 for STT, 8005 for TTS)
#   --http-port     HTTP port (default: 8003 for LLM, 8004 for STT, 8006 for TTS)
#
# Examples:
#   ./scripts/generate_nim_compose_snippet.sh --stt --image nvcr.io/nim/riva/riva-asr:1.0.0
#   ./scripts/generate_nim_compose_snippet.sh --tts --image nvcr.io/nim/riva/riva-tts:1.0.0

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

GENERATE_STT=false
GENERATE_TTS=false
IMAGE=""
SERVICE_NAME=""
GRPC_PORT=""
HTTP_PORT=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --stt)
            GENERATE_STT=true
            shift
            ;;
        --tts)
            GENERATE_TTS=true
            shift
            ;;
        --image)
            IMAGE="$2"
            shift 2
            ;;
        --name)
            SERVICE_NAME="$2"
            shift 2
            ;;
        --grpc-port)
            GRPC_PORT="$2"
            shift 2
            ;;
        --http-port)
            HTTP_PORT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--stt] [--tts] [--image IMAGE] [--name NAME] [--grpc-port PORT] [--http-port PORT]"
            exit 1
            ;;
    esac
done

# Determine defaults based on type
if [ "$GENERATE_STT" = true ]; then
    SERVICE_NAME="${SERVICE_NAME:-nim-riva-asr}"
    GRPC_PORT="${GRPC_PORT:-8002}"
    HTTP_PORT="${HTTP_PORT:-8004}"
    CONTAINER_NAME="common-nim-riva-asr"
    IMAGE="${IMAGE:-nvcr.io/nim/riva/riva-asr:latest}"
    TYPE_DESC="Riva ASR (Speech-to-Text)"
elif [ "$GENERATE_TTS" = true ]; then
    SERVICE_NAME="${SERVICE_NAME:-nim-riva-tts}"
    GRPC_PORT="${GRPC_PORT:-8005}"
    HTTP_PORT="${HTTP_PORT:-8006}"
    CONTAINER_NAME="common-nim-riva-tts"
    IMAGE="${IMAGE:-nvcr.io/nim/riva/riva-tts:latest}"
    TYPE_DESC="Riva TTS (Text-to-Speech)"
else
    echo "Error: Must specify --stt or --tts"
    echo "Usage: $0 [--stt] [--tts] [--image IMAGE] [--name NAME] [--grpc-port PORT] [--http-port PORT]"
    exit 1
fi

echo "# ${TYPE_DESC} NIM Service"
echo "# Generated by: scripts/generate_nim_compose_snippet.sh"
echo "#"
echo "# This service provides ${TYPE_DESC} inference via NVIDIA NIM container."
echo "# Requires NGC_API_KEY for authentication."
echo "#"
echo "# Note: Verify ARM64/DGX Spark compatibility before deploying:"
echo "#   - Check NGC catalog: https://catalog.ngc.nvidia.com/"
echo "#   - Verify image path and architecture support"
FILTER_TYPE=$([ "$GENERATE_STT" = true ] && echo "stt" || echo "tts")
echo "#   - Use: poetry run python -m essence list-nims --filter ${FILTER_TYPE} --dgx-spark-only"
echo "#"
echo "${SERVICE_NAME}:"
echo "  image: ${IMAGE}"
echo "  container_name: ${CONTAINER_NAME}"
echo "  restart: unless-stopped"
echo "  expose:"
echo "    - \"${GRPC_PORT}\"  # gRPC endpoint (internal to shared-network, accessible as ${SERVICE_NAME}:${GRPC_PORT})"
echo "    - \"${HTTP_PORT}\"  # HTTP endpoint (internal, for health checks)"
echo "  environment:"
echo "    - CUDA_VISIBLE_DEVICES=0"
echo "    - NGC_API_KEY=\${NGC_API_KEY}  # Required for NGC container access"
echo "    - ENABLE_TRACING=\${ENABLE_TRACING:-true}"
echo "    - JAEGER_ENDPOINT=http://common-jaeger:14268/api/traces"
echo "    - JAEGER_AGENT_HOST=common-jaeger"
echo "    - JAEGER_AGENT_PORT=6831"
echo "  deploy:"
echo "    resources:"
echo "      reservations:"
echo "        devices:"
echo "          - driver: nvidia"
echo "            device_ids:"
echo "              - '0'"
echo "            capabilities:"
echo "              - gpu"
echo "  volumes:"
echo "    - \${MODEL_CACHE_DIR:-/home/rlee/models}:/models"
echo "    - /var/log/june/${SERVICE_NAME}:/logs"
echo "    - /var/data/june/${SERVICE_NAME}:/data"
echo "  networks:"
echo "    - shared-network"
echo "  healthcheck:"
echo "    test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:${HTTP_PORT}/health\"]"
echo "    interval: 30s"
echo "    timeout: 10s"
echo "    retries: 3"
echo "    start_period: 120s  # Allow time for model loading"
echo "  # Note: NIMs are pre-built containers from NVIDIA NGC"
echo "  # No model compilation required - containers include optimized models"
echo ""
